test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: "/home/ylwang/dataset/benchmark/Set14/HR/"
  wrapper:
    name: sr-implicit-downsampled-sample
    args:
      scale_min: 6
  batch_size: 1 
eval_type: benchmark-6
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}