test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: "/home/ylwang/dataset/benchmark/Urban100/LR_bicubic/X4/"
      root_path_2: "/home/ylwang/dataset/benchmark/Urban100/HR/"
  wrapper:
    name: regular-sampled-and-map
    ratio: 0.5
    args: {}
  batch_size: 1
eval_type: benchmark-4
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}