test_dataset: 
  dataset:
    name: image-folder
    args:
      root_path: "/home/ylwang/dataset/Set14/original"
  wrapper:
    name: regular-sampled
    args: 
      ratio_min: 0.2
      normalize: False
      seed: 1
  batch_size: 1
eval_type: benchmark-1
eval_bsize: 30000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}