test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: "/home/ylwang/dataset/benchmark/Set5/HR/"
  wrapper:
    name: sr-implicit-downsampled-sample
    args:
      scale_min: 8
  batch_size: 1
eval_type: benchmark-8
eval_bsize: 10

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}