test_dataset:
  dataset:
    name: image-folder
    args:
      root_path: "/home/ylwang/dataset/draw/"
  wrapper:
    name: irregular-sampled-test-arbitrary
    args: 
      scale_min: 0.2
      normalize: False
      seed: 5
  batch_size: 1
eval_type: div2k-2
eval_bsize: 1000

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}